---
- name: Setup /opt/devops directory and info.txt
  hosts: all
  become: true
  tasks:
    - name: Ensure /opt/devops directory exists
      file:
        path: /opt/devops
        state: directory

    - name: Create info.txt with message
      copy:
        dest: /opt/devops/info.txt
        content: "Hello from Ansible!\n"
...

